name: Spring Boot CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Copy JAR file via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "target/GalacticStories-v1.jar" #test
          target: "~/gsapiserver"

      - name: Restart Spring Boot App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            pkill java
            # Set the end time for the log file renaming
            END_TIME=$(date +"%Y-%m-%d_%H-%M-%S")
            
            # Locate the existing log file using a wildcard and rename it
            for logfile in ~/gsapiserver/galacticstories_started_*.log; do
              if [ -f "$logfile" ]; then
                # Rename the existing log file by appending the end time.
                mv "$logfile" ~/gsapiserver/old_logs/$(basename "$logfile" .log)_end_${END_TIME}.log
              fi
            done
          
            # Start a new instance of the server. The new log file includes the start time in its name.
            nohup java -Djava.net.preferIPv4Stack=true -jar ~/gsapiserver/target/GalacticStories-v1.jar > ~/gsapiserver/galacticstories_started_$(date +"%Y-%m-%d_%H-%M-%S").log 2>&1 &
            disown
